# Generated by Django 4.0 on 2021-12-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_deleted_blog_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
